# Generated by Django 3.2 on 2021-07-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
